# Generated by Django 4.0 on 2021-12-18 14:24

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('billing', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='ItemList',
            new_name='ItemLine',
        ),
    ]
